version: "3.1"

services:
  postgres:
    image: postgres:13
    container_name: orangutan_postgres_db
    environment:
      POSTGRES_USER: orangutan_admin
      POSTGRES_PASSWORD: G@V7xh!83kR*2Jz
      POSTGRES_DB: orangutan_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
