databaseChangeLog:
  - changeSet:
      id: 28
      author: kacper
      changes:
        - createTable:
            tableName: trainingexercises
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
                  comment: "ID, PK, dodany autoincrement" 
              - column:
                  name: userid
                  type: INT
                  constraints:
                    nullable: false
                  comment: "ID z tablicy users, FK" 
              - column:
                  name: trainingid
                  type: INT
                  constraints:
                    nullable: false
                  comment: "ID z tablicy training, FK"
              - column:
                  name: exerciseid
                  type: INT
                  constraints:
                    nullable: false
                  comment: "ID z tablicy exercises, FK"
              - column:
                  name: minsetnumber
                  type: INT
                  constraints:
                    nullable: true
                  comment: "Minimalna liczba serii"
              - column:
                  name: maxsetnumber
                  type: INT
                  constraints:
                    nullable: true
                  comment: "Maksymalna liczba serii"
              - addForeignKeyConstraint:
                  baseTableName: trainingexercises
                  baseColumnNames: userid
                  referencedTableName: users
                  referencedColumnNames: id
                  constraintName: fk_usr2traex
              - addForeignKeyConstraint:
                  baseTableName: trainingexercises
                  baseColumnNames: trainingid
                  referencedTableName: training
                  referencedColumnNames: id
                  constraintName: fk_tra2traex
              - addForeignKeyConstraint:
                  baseTableName: trainingexercises
                  baseColumnNames: exerciseid
                  referencedTableName: exercises
                  referencedColumnNames: id
                  constraintName: fk_ex2traex